{% set name = "clouddrift" %}
{% set version = "0.21.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/clouddrift-{{ version }}.tar.gz
  sha256: 4aaa05cee18e673b5da0ce6fbf78f284d7c49948ca6fc7719271ffe6f45b4d63

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - pip
  run:
    - python >=3.9
    - numpy >=1.21.6
    - xarray >=2023.5.0
    - pandas >=1.3.4
    - netcdf4 >=1.6.4
    - pyarrow >=9.0.0
    - tqdm >=4.64.1
    - fsspec >=2022.8.2
    - llvmlite >=0.38.1
    - awkward >=2.0.0
    - aiohttp >=3.8.4
    - requests >=2.31.0
    - scipy >=1.11.2
    - zarr >=2.14.2

test:
  imports:
    - clouddrift
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/clouddrift/
  summary: Accelerating the use of Lagrangian data for atmospheric, oceanic, and climate sciences
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - philippemiron
    - selipot
